import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { AmplifyProvider } from "@/components/AmplifyProvider";
import { OrientationLock } from "@/components/OrientationLock";
import "./reset.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <AmplifyProvider>
          <OrientationLock />
          {children}
          <Toaster richColors position="top-center" />
        </AmplifyProvider>
      </body>
    </html>
  );
}
